export const APPOINTMENT_ADD_REQUEST = 'APPOINTMENT_ADD_REQUEST';
export const APPOINTMENT_ADD_SUCCESS = 'APPOINTMENT_ADD_SUCCESS';
export const APPOINTMENT_ADD_FAIL = 'APPOINTMENT_ADD_FAIL';
export const APPOINTMENT_ADD_RESET = 'APPOINTMENT_ADD_RESET';

export const APPOINTMENT_UPDATE_PAYMENT_REQUEST = 'APPOINTMENT_UPDATE_PAYMENT_REQUEST';
export const APPOINTMENT_UPDATE_PAYMENT_SUCCESS = 'APPOINTMENT_UPDATE_PAYMENT_SUCCESS';
export const APPOINTMENT_UPDATE_PAYMENT_FAIL = 'APPOINTMENT_UPDATE_PAYMENT_FAIL';
export const APPOINTMENT_UPDATE_PAYMENT_RESET = 'APPOINTMENT_UPDATE_PAYMENT_RESET';

export const APPOINTMENT_DELETE_REQUEST = 'APPOINTMENT_DELETE_REQUEST';
export const APPOINTMENT_DELETE_SUCCESS = 'APPOINTMENT_DELETE_SUCCESS';
export const APPOINTMENT_DELETE_FAIL = 'APPOINTMENT_DELETE_FAIL';
export const APPOINTMENT_DELETE_RESET = 'APPOINTMENT_DELETE_RESET';

export const USER_APPOINTMENT_LIST_REQUEST = 'USER_APPOINTMENT_LIST_REQUEST';
export const USER_APPOINTMENT_LIST_SUCCESS = 'USER_APPOINTMENT_LIST_SUCCESS';
export const USER_APPOINTMENT_LIST_FAIL = 'USER_APPOINTMENT_LIST_FAIL';
export const USER_APPOINTMENT_LIST_RESET = 'USER_APPOINTMENT_LIST_RESET';

export const ALL_APPOINTMENT_OF_DAY_REQUEST = 'ALL_APPOINTMENT_OF_DAY_REQUEST';
export const ALL_APPOINTMENT_OF_DAY_SUCCESS = 'ALL_APPOINTMENT_OF_DAY_SUCCESS';
export const ALL_APPOINTMENT_OF_DAY_FAIL = 'ALL_APPOINTMENT_OF_DAY_FAIL';
export const ALL_APPOINTMENT_OF_DAY_RESET = 'ALL_APPOINTMENT_OF_DAY_RESET';

export const APPOINTMENT_OF_DAY_REQUEST = 'APPOINTMENT_OF_DAY_REQUEST';
export const APPOINTMENT_OF_DAY_SUCCESS = 'APPOINTMENT_OF_DAY_SUCCESS';
export const APPOINTMENT_OF_DAY_FAIL = 'APPOINTMENT_OF_DAY_FAIL';
export const APPOINTMENT_OF_DAY_RESET = 'APPOINTMENT_OF_DAY_RESET';

export const APPOINTMENT_SET_IN_PROGRESS_REQUEST = 'APPOINTMENT_SET_IN_PROGRESS_REQUEST';
export const APPOINTMENT_SET_IN_PROGRESS_SUCCESS = 'APPOINTMENT_SET_IN_PROGRESS_SUCCESS';
export const APPOINTMENT_SET_IN_PROGRESS_FAIL = 'APPOINTMENT_SET_IN_PROGRESS_FAIL';
export const APPOINTMENT_SET_IN_PROGRESS_RESET = 'APPOINTMENT_SET_IN_PROGRESS_RESET';

export const APPOINTMENT_SET_COMPLETE_REQUEST = 'APPOINTMENT_SET_COMPLETE_REQUEST';
export const APPOINTMENT_SET_COMPLETE_SUCCESS = 'APPOINTMENT_SET_COMPLETE_SUCCESS';
export const APPOINTMENT_SET_COMPLETE_FAIL = 'APPOINTMENT_SET_COMPLETE_FAIL';
export const APPOINTMENT_SET_COMPLETE_RESET = 'APPOINTMENT_SET_COMPLETE_RESET';