export const APPOINTMENT_ADD_REQUEST = 'APPOINTMENT_ADD_REQUEST';
export const APPOINTMENT_ADD_SUCCESS = 'APPOINTMENT_ADD_SUCCESS';
export const APPOINTMENT_ADD_FAIL = 'APPOINTMENT_ADD_FAIL';
export const APPOINTMENT_ADD_RESET = 'APPOINTMENT_ADD_RESET';

export const APPOINTMENT_UPDATE_PAYMENT_REQUEST = 'APPOINTMENT_UPDATE_PAYMENT_REQUEST';
export const APPOINTMENT_UPDATE_PAYMENT_SUCCESS = 'APPOINTMENT_UPDATE_PAYMENT_SUCCESS';
export const APPOINTMENT_UPDATE_PAYMENT_FAIL = 'APPOINTMENT_UPDATE_PAYMENT_FAIL';
export const APPOINTMENT_UPDATE_PAYMENT_RESET = 'APPOINTMENT_UPDATE_PAYMENT_RESET';

export const APPOINTMENT_DELETE_REQUEST = 'APPOINTMENT_DELETE_REQUEST';
export const APPOINTMENT_DELETE_SUCCESS = 'APPOINTMENT_DELETE_SUCCESS';
export const APPOINTMENT_DELETE_FAIL = 'APPOINTMENT_DELETE_FAIL';
export const APPOINTMENT_DELETE_RESET = 'APPOINTMENT_DELETE_RESET';

export const USER_APPOINTMENT_LIST_REQUEST = 'USER_APPOINTMENT_LIST_REQUEST';
export const USER_APPOINTMENT_LIST_SUCCESS = 'USER_APPOINTMENT_LIST_SUCCESS';
export const USER_APPOINTMENT_LIST_FAIL = 'USER_APPOINTMENT_LIST_FAIL';
export const USER_APPOINTMENT_LIST_RESET = 'USER_APPOINTMENT_LIST_RESET';