export const BLOG_LIST_REQUEST = 'BLOG_LIST_REQUEST';
export const BLOG_LIST_SUCCESS = 'BLOG_LIST_SUCCESS';
export const BLOG_LIST_FAIL = 'BLOG_LIST_FAIL';

export const BLOG_DELETE_REQUEST = 'BLOG_DELETE_REQUEST';
export const BLOG_DELETE_SUCCESS = 'BLOG_DELETE_SUCCESS';
export const BLOG_DELETE_FAIL = 'BLOG_DELETE_FAIL';
export const BLOG_DELETE_RESET = 'BLOG_DELETE_RESET';

export const BLOG_DETAILS_REQUEST = 'BLOG_DETAILS_REQUEST';
export const BLOG_DETAILS_SUCCESS = 'BLOG_DETAILS_SUCCESS';
export const BLOG_DETAILS_FAIL = 'BLOG_DETAILS_FAIL';
export const BLOG_DETAILS_RESET = 'BLOG_DETAILS_RESET';

export const BLOG_UPDATE_REQUEST = 'BLOG_UPDATE_REQUEST';
export const BLOG_UPDATE_SUCCESS = 'BLOG_UPDATE_SUCCESS';
export const BLOG_UPDATE_RESET = 'BLOG_UPDATE_RESET';
export const BLOG_UPDATE_FAIL = 'BLOG_UPDATE_FAIL';

export const BLOG_ADD_REQUEST = 'BLOG_ADD_REQUEST';
export const BLOG_ADD_SUCCESS = 'BLOG_ADD_SUCCESS';
export const BLOG_ADD_FAIL = 'BLOG_ADD_FAIL';
export const BLOG_ADD_RESET = 'BLOG_ADD_RESET';

export const BLOG_ADD_IMAGE_REQUEST = 'BLOG_ADD_IMAGE_REQUEST';
export const BLOG_ADD_IMAGE_SUCCESS = 'BLOG_ADD_IMAGE_SUCCESS';
export const BLOG_ADD_IMAGE_FAIL = 'BLOG_ADD_IMAGE_FAIL';
export const BLOG_ADD_IMAGE_RESET = 'BLOG_ADD_IMAGE_RESET'