export const CAR_LIST_REQUEST = 'CAR_LIST_REQUEST';
export const CAR_LIST_SUCCESS = 'CAR_LIST_SUCCESS';
export const CAR_LIST_FAIL = 'CAR_LIST_FAIL';
export const CAR_LIST_RESET = 'CAR_LIST_RESET';

export const CAR_DETAILS_REQUEST = 'CAR_DETAILS_REQUEST';
export const CAR_DETAILS_SUCCESS = 'CAR_DETAILS_SUCCESS';
export const CAR_DETAILS_FAIL = 'CAR_DETAILS_FAIL';

export const CAR_FAULTS_REQUEST = 'CAR_FAULTS_REQUEST';
export const CAR_FAULTS_SUCCESS = 'CAR_FAULTS_SUCCESS';
export const CAR_FAULTS_FAIL = 'CAR_FAULTS_FAIL';

export const CAR_DELETE_REQUEST = 'CAR_DELETE_REQUEST';
export const CAR_DELETE_SUCCESS = 'CAR_DELETE_SUCCESS';
export const CAR_DELETE_FAIL = 'CAR_DELETE_FAIL';
export const CAR_DELETE_RESET = 'CAR_DELETE_RESET';

export const CAR_ADD_REQUEST = 'CAR_ADD_REQUEST';
export const CAR_ADD_SUCCESS = 'CAR_ADD_SUCCESS';
export const CAR_ADD_FAIL = 'CAR_ADD_FAIL';
export const CAR_ADD_RESET = 'CAR_ADD_RESET'

export const CAR_ADD_IMAGE_REQUEST = 'CAR_ADD_IMAGE_REQUEST';
export const CAR_ADD_IMAGE_SUCCESS = 'CAR_ADD_IMAGE_SUCCESS';
export const CAR_ADD_IMAGE_FAIL = 'CAR_ADD_IMAGE_FAIL';
export const CAR_ADD_IMAGE_RESET = 'CAR_ADD_IMAGE_RESET'
