export const EMAIL_CONTACT_SEND_REQUEST = 'EMAIL_CONTACT_SEND_REQUEST';
export const EMAIL_CONTACT_SEND_SUCCESS = 'EMAIL_CONTACT_SEND_SUCCESS';
export const EMAIL_CONTACT_SEND_FAIL = 'EMAIL_CONTACT_SEND_FAIL';
export const EMAIL_CONTACT_SEND_RESET = 'EMAIL_CONTACT_SEND_RESET';