export const MECHANICAL_SERVICES_LIST_REQUEST = 'MECHANICAL_SERVICES_LIST_REQUEST';
export const MECHANICAL_SERVICES_LIST_SUCCESS = 'MECHANICAL_SERVICES_LIST_SUCCESS';
export const MECHANICAL_SERVICES_FAIL = 'MECHANICAL_SERVICES_LIST_FAIL';

export const MECHANICAL_SERVICE_DELETE_REQUEST = 'MECHANICAL_SERVICE_DELETE_REQUEST';
export const MECHANICAL_SERVICE_DELETE_SUCCESS = 'MECHANICAL_SERVICE_DELETE_SUCCESS';
export const MECHANICAL_SERVICE_DELETE_FAIL = 'MECHANICAL_SERVICE_DELETE_FAIL';
export const MECHANICAL_SERVICE_DELETE_RESET = 'MECHANICAL_SERVICE_DELETE_RESET';

export const MECHANICAL_SERVICE_DETAILS_REQUEST = 'MECHANICAL_SERVICE_DETAILS_REQUEST';
export const MECHANICAL_SERVICE_DETAILS_SUCCESS = 'MECHANICAL_SERVICE_DETAILS_SUCCESS';
export const MECHANICAL_SERVICE_DETAILS_FAIL = 'MECHANICAL_SERVICE_DETAILS_FAIL';
export const MECHANICAL_SERVICE_DETAILS_RESET = 'MECHANICAL_SERVICE_DETAILS_RESET';

export const MECHANICAL_SERVICE_UPDATE_REQUEST = 'MECHANICAL_SERVICE_UPDATE_REQUEST';
export const MECHANICAL_SERVICE_UPDATE_SUCCESS = 'MECHANICAL_SERVICE_UPDATE_SUCCESS';
export const MECHANICAL_SERVICE_UPDATE_FAIL = 'MECHANICAL_SERVICE_UPDATE_FAIL';
export const MECHANICAL_SERVICE_UPDATE_RESET = 'MECHANICAL_SERVICE_UPDATE_RESET';

export const MECHANICAL_SERVICE_ADD_REQUEST = 'MECHANICAL_SERVICE_ADD_REQUEST';
export const MECHANICAL_SERVICE_ADD_SUCCESS = 'MECHANICAL_SERVICE_ADD_SUCCESS';
export const MECHANICAL_SERVICE_ADD_FAIL = 'MECHANICAL_SERVICE_ADD_FAIL';
export const MECHANICAL_SERVICE_ADD_RESET = 'MECHANICAL_SERVICE_ADD_RESET';