export const MECHANICAL_SERVICES_LIST_REQUEST = 'MECHANICAL_SERVICES_LIST_REQUEST';
export const MECHANICAL_SERVICES_LIST_SUCCESS = 'MECHANICAL_SERVICES_LIST_SUCCESS';
export const MECHANICAL_SERVICES_FAIL = 'MECHANICAL_SERVICES_LIST_FAIL';