export const RABAT_CODE_DISCOUNT_REQUEST = 'RABAT_CODE_DISCOUNT_REQUEST';
export const RABAT_CODE_DISCOUNT_SUCCESS = 'RABAT_CODE_DISCOUNT_SUCCESS';
export const RABAT_CODE_DISCOUNT_FAIL = 'RABAT_CODE_DISCOUNT_FAIL';