export const RABAT_CODE_DISCOUNT_REQUEST = 'RABAT_CODE_DISCOUNT_REQUEST';
export const RABAT_CODE_DISCOUNT_SUCCESS = 'RABAT_CODE_DISCOUNT_SUCCESS';
export const RABAT_CODE_DISCOUNT_FAIL = 'RABAT_CODE_DISCOUNT_FAIL';
export const RABAT_CODE_DISCOUNT_RESET = 'RABAT_CODE_DISCOUNT_RESET';

export const RABAT_CODES_LIST_REQUEST = 'RABAT_CODES_LIST_REQUEST';
export const RABAT_CODES_LIST_SUCCESS = 'RABAT_CODES_LIST_SUCCESS';
export const RABAT_CODES_LIST_FAIL = 'RABAT_CODES_LIST_FAIL';

export const RABAT_CODE_DELETE_REQUEST = 'RABAT_CODE_DELETE_REQUEST';
export const RABAT_CODE_DELETE_SUCCESS = 'RABAT_CODE_DELETE_SUCCESS';
export const RABAT_CODE_DELETE_FAIL = 'RABAT_CODE_DELETE_FAIL';
export const RABAT_CODE_DELETE_RESET = 'RABAT_CODE_DELETE_RESET';

export const RABAT_CODE_DETAILS_REQUEST = 'RABAT_CODE_DETAILS_REQUEST';
export const RABAT_CODE_DETAILS_SUCCESS = 'RABAT_CODE_DETAILS_SUCCESS';
export const RABAT_CODE_DETAILS_FAIL = 'RABAT_CODE_DETAILS_FAIL';
export const RABAT_CODE_DETAILS_RESET = 'RABAT_CODE_DETAILS_RESET';

export const RABAT_CODE_UPDATE_REQUEST = 'RABAT_CODE_UPDATE_REQUEST';
export const RABAT_CODE_UPDATE_SUCCESS = 'RABAT_CODE_UPDATE_SUCCESS';
export const RABAT_CODE_UPDATE_FAIL = 'RABAT_CODE_UPDATE_FAIL';
export const RABAT_CODE_UPDATE_RESET = 'RABAT_CODE_UPDATE_RESET';

export const RABAT_CODE_ADD_REQUEST = 'RABAT_CODE_ADD_REQUEST';
export const RABAT_CODE_ADD_SUCCESS = 'RABAT_CODE_ADD_SUCCESS';
export const RABAT_CODE_ADD_FAIL = 'RABAT_CODE_ADD_FAIL';
export const RABAT_CODE_ADD_RESET = 'RABAT_CODE_ADD_RESET';