export const USER_SIGNIN_REQUEST = 'USER_SIGNIN_REQUEST';
export const USER_SIGNIN_SUCCESS = 'USER_SIGNIN_SUCCESS';
export const USER_SIGNIN_FAIL = 'USER_SIGNIN_FAIL';
export const USER_SIGNOUT = 'USER_SIGNOUT';

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL';
export const USER_REGISTER_RESET = 'USER_REGISTER_RESET';

export const USER_DETAILS_REQUEST = 'USER_DETAILS_REQUEST';
export const USER_DETAILS_SUCCESS = 'USER_DETAILS_SUCCESS';
export const USER_DETAILS_FAIL = 'USER_DETAILS_FAIL';
export const USER_DETAILS_RESET = 'USER_DETAILS_RESET';

export const USER_UPDATE_PROFILE_REQUEST = 'USER_UPDATE_PROFILE_REQUEST';
export const USER_UPDATE_PROFILE_SUCCESS = 'USER_UPDATE_PROFILE_SUCCESS';
export const USER_UPDATE_PROFILE_FAIL = 'USER_UPDATE_PROFILE_FAIL';
export const USER_UPDATE_PROFILE_RESET = 'USER_UPDATE_PROFILE_RESET';

export const GET_USER_ROLE_REQUEST = 'GET_USER_ROLE_REQUEST';
export const GET_USER_ROLE_SUCCESS = 'GET_USER_ROLE_SUCCESS';
export const GET_USER_ROLE_FAIL = 'GET_USER_ROLE_FAIL';
export const GET_USER_ROLE_RESET = 'GET_USER_ROLE_RESET';

export const GET_USERS_WITH_USER_ROLE_REQUEST = 'GET_USERS_WITH_USER_ROLE_REQUEST';
export const GET_USERS_WITH_USER_ROLE_SUCCESS = 'GET_USERS_WITH_USER_ROLE_SUCCESS';
export const GET_USERS_WITH_USER_ROLE_FAIL = 'GET_USERS_WITH_USER_ROLE_FAIL';
export const GET_USERS_WITH_USER_ROLE_RESET = 'GET_USERS_WITH_USER_ROLE_RESET';

export const GET_USERS_WITH_EMPLOYEE_ROLE_REQUEST = 'GET_USERS_WITH_EMPLOYEE_ROLE_REQUEST';
export const GET_USERS_WITH_EMPLOYEE_ROLE_SUCCESS = 'GET_USERS_WITH_EMPLOYEE_ROLE_SUCCESS';
export const GET_USERS_WITH_EMPLOYEE_ROLE_FAIL = 'GET_USERS_WITH_EMPLOYEE_ROLE_FAIL';
export const GET_USERS_WITH_EMPLOYEE_ROLE_RESET = 'GET_USERS_WITH_EMPLOYEE_ROLE_RESET';

export const GET_USERS_WITH_ADMIN_ROLE_REQUEST = 'GET_USERS_WITH_ADMIN_ROLE_REQUEST';
export const GET_USERS_WITH_ADMIN_ROLE_SUCCESS = 'GET_USERS_WITH_ADMIN_ROLE_SUCCESS';
export const GET_USERS_WITH_ADMIN_ROLE_FAIL = 'GET_USERS_WITH_ADMIN_ROLE_FAIL';
export const GET_USERS_WITH_ADMIN_ROLE_RESET = 'GET_USERS_WITH_ADMIN_ROLE_RESET';

export const GET_USER_FOR_ADMIN_REQUEST = 'GET_USER_FOR_ADMIN_REQUEST';
export const GET_USER_FOR_ADMIN_SUCCESS = 'GET_USER_FOR_ADMIN_SUCCESS';
export const GET_USER_FOR_ADMIN_FAIL = 'GET_USER_FOR_ADMIN_FAIL';
export const GET_USER_FOR_ADMIN_RESET = 'GET_USER_FOR_ADMIN_RESET';

export const UPDATE_USER_BY_ADMIN_REQUEST = 'UPDATE_USER_BY_ADMIN_REQUEST';
export const UPDATE_USER_BY_ADMIN_SUCCESS = 'UPDATE_USER_BY_ADMIN_SUCCESS';
export const UPDATE_USER_BY_ADMIN_FAIL = 'UPDATE_USER_BY_ADMIN_FAIL';
export const UPDATE_USER_BY_ADMIN_RESET = 'UPDATE_USER_BY_ADMIN_RESET';

export const CHECK_USER_REGULAR_CUSTOMER_REQUEST = 'CHECK_USER_REGULAR_CUSTOMER_REQUEST';
export const CHECK_USER_REGULAR_CUSTOMER_SUCCESS = 'CHECK_USER_REGULAR_CUSTOMER_SUCCESS';
export const CHECK_USER_REGULAR_CUSTOMER_FAIL = 'CHECK_USER_REGULAR_CUSTOMER_FAIL';
export const CHECK_USER_REGULAR_CUSTOMER_RESET = 'CHECK_USER_REGULAR_CUSTOMER_RESET';

export const USER_REGISTER_BY_ADMIN_REQUEST = 'USER_REGISTER_BY_ADMIN_REQUEST';
export const USER_REGISTER_BY_ADMIN_SUCCESS = 'USER_REGISTER_BY_ADMIN_SUCCESS';
export const USER_REGISTER_BY_ADMIN_FAIL = 'USER_REGISTER_BY_ADMIN_FAIL';
export const USER_REGISTER_BY_ADMIN_RESET = 'USER_REGISTER_BY_ADMIN_FAIL';

export const USER_DELETE_BY_ADMIN_REQUEST = 'USER_DELETE_BY_ADMIN_REQUEST';
export const USER_DELETE_BY_ADMIN_SUCCESS = 'USER_DELETE_BY_ADMIN_SUCCESS';
export const USER_DELETE_BY_ADMIN_FAIL = 'USER_DELETE_BY_ADMIN_FAIL';
export const USER_DELETE_BY_ADMIN_RESET = 'USER_DELETE_BY_ADMIN_RESET';