export const AVAILABLE_WORKING_PERIOD_LIST_REQUEST = 'AVAILABLE_WORKING_PERIOD_REQUEST';
export const AVAILABLE_WORKING_PERIOD_LIST_SUCCESS = 'AVAILABLE_WORKING_PERIOD_SUCCESS';
export const AVAILABLE_WORKING_PERIOD_FAIL = 'AVAILABLE_WORKING_PERIOD_FAIL';
export const AVAILABLE_WORKING_PERIOD_RESET = 'AVAILABLE_WORKING_PERIOD_RESET';