version: '3.8'

services:

  database:
    image: 'postgres:14.4'

    ports:
      - 5432:5432

    environment:
      POSTGRES_USER: carclinicuser
      POSTGRES_PASSWORD: carclinicPwd
      POSTGRES_DB: carclinic