spring:
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQL81Dialect
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 30MB
  datasource:
    url: 'jdbc:postgresql://localhost:5432/carclinic'
    username: carclinicuser
    password: carclinicPwd
  liquibase:
    change-log: classpath:liquibase-changeLog.xml
cors:
  allowUrl: "*"
jwt:
  secret: secret_code
  expirationTime: 30h
captcha:
  secret: NkxlSXhBY1RBQUFBQUdHLXZGSTFUblJXeE1aTkZ1b2pKNFdpZkpXZQ==
  url: https://www.google.com/recaptcha/api/siteverify
rest:
  connection:
    connectionRequestTimeout: 5s
    readTimeout: 10s

files-storage:
  path: 'backend/src/main/resources/files'

cars:
  images-path: 'cars'

blog:
  images-path: 'blog'

mail:
  admin: carclinic.superuser@gmail.com
  sender:
    password: zjtsbysytukmajli
    debug: false
    user: carclinic.superuser@gmail.com
    host: smtp.gmail.com
    port: 587
  add-appointment:
    subject: 'Dodano rezerwację usługi w serwisie CarClinic!'
    pathToMessage: '/content/mail/addAppointment_pl.html'
  add-appointment-to-employee:
    subject: 'Dodano rezerwację usługi w serwisie CarClinic!'
    pathToMessage: '/content/mail/addAppointment_Message_To_Employee_pl.html'
  send-notification:
    subject: 'Czy wymieniłeś już olej i filtry w swoim samochodzie?'
    pathToMessage: '/content/mail/sendNotificationToUsersWithCars.html'
  contact:
    pathToMessage: '/content/mail/contact.html'
  complete-appointment:
    subject: 'Twoje zgłoszenie w serwisie CarClinic zostało wykonane!'
    pathToMessage: '/content/mail/completeAppointment.html'
  complete-appointment-remote:
    subject: 'Twoje zgłoszenie w serwisie CarClinic zostało wykonane!'
    pathToMessage: '/content/mail/completeAppointmentRemote.html'
  in-progress-appointment:
    subject: 'Twoje zgłoszenie w CarClinic jest w trakcie rozpatrywania!'
    pathToMessage: '/content/mail/inProgressAppointment.html'
  cancel-appointment:
    subject: 'Zgłoszenie w CarClinic zostało anulowane!'
    pathToMessage: '/content/mail/cancelAppointment.html'