spring:
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQL81Dialect
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 30MB
  datasource:
    url: 'jdbc:postgresql://localhost:5432/carclinic'
    username: carclinicuser
    password: carclinicPwd
  liquibase:
    change-log: classpath:liquibase-changeLog.xml
cors:
  allowUrl: "*"
jwt:
  secret: secret_code
  expirationTime: 30h
captcha:
  secret: NkxlSXhBY1RBQUFBQUdHLXZGSTFUblJXeE1aTkZ1b2pKNFdpZkpXZQ==
  url: https://www.google.com/recaptcha/api/siteverify
rest:
  connection:
    connectionRequestTimeout: 5s
    readTimeout: 10s

files-storage:
  path: 'backend/src/main/resources/files'

errorreports:
  images-path: 'report'